In [1]:
from tfrecordManager import tfrecordManager

#### Loads tfrecords for audio datasets in Patset.

In [2]:
tfr = tfrecordManager()

In [3]:
# Take a single record from a file
filename = ["sampleDir/shard0.tfrecord"]
data_record = tfr.__printRecord__(filename[0])
data_record

features {
  feature {
    key: "audio"
    value {
      float_list {
        value: 0.0
        value: 0.08991377800703049
        value: 0.17905618250370026
        value: 0.2667750418186188
        value: 0.35241708159446716
        value: 0.43534478545188904
        value: 0.5149411559104919
        value: 0.5906144380569458
        value: 0.6618022918701172
        value: 0.7279763221740723
        value: 0.7886457443237305
        value: 0.8433611989021301
        value: 0.8917178511619568
        value: 0.933358907699585
        value: 0.96797776222229
        value: 0.9953204989433289
        value: 1.0151878595352173
        value: 1.02743661403656
        value: 1.0319806337356567
        value: 1.0287914276123047
        value: 1.017898678779602
        value: 0.9993897080421448
        value: 0.9734087586402893
        value: 0.9401561617851257
        value: 0.8998866081237793
        value: 0.8529074192047119
        value: 0.7995759844779968
        value: 0.74029731750

#### Load single records

In [4]:
# Get feature list as JSON
tfr.__getFeatures__(data_record)

[['audio', 'float_list'],
 ['cf_synth_minval', 'float_list'],
 ['cf_user_maxval', 'float_list'],
 ['segmentNum', 'int64_list'],
 ['irreg_exp_synth_maxval', 'float_list'],
 ['cf', 'float_list'],
 ['rate_exp_synth_units', 'bytes_list'],
 ['irreg_exp_user_minval', 'float_list'],
 ['cf_synth_units', 'bytes_list'],
 ['rate_exp_user_minval', 'float_list'],
 ['rate_exp_synth_maxval', 'float_list'],
 ['irreg_exp_synth_minval', 'float_list'],
 ['rate_exp_user_maxval', 'float_list'],
 ['pfname', 'bytes_list'],
 ['cf_user_minval', 'float_list'],
 ['irreg_exp_user_nvals', 'int64_list'],
 ['irreg_exp_user_maxval', 'float_list'],
 ['rate_exp', 'float_list'],
 ['soundDuration', 'float_list'],
 ['cf_user_nvals', 'int64_list'],
 ['irreg_exp', 'float_list'],
 ['cf_synth_maxval', 'float_list'],
 ['rate_exp_user_nvals', 'int64_list'],
 ['irreg_exp_synth_units', 'bytes_list'],
 ['rate_exp_synth_minval', 'float_list']]

In [5]:
# Use feature list to read serialized TFrecords
tfr.__readOne__(filename)

{'audio': <tf.Tensor: shape=(32000,), dtype=float32, numpy=
array([0.        , 0.08991378, 0.17905618, ..., 0.        , 0.        ,
       0.        ], dtype=float32)>, 'cf': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([220.], dtype=float32)>, 'cf_synth_maxval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'cf_synth_minval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'cf_synth_units': <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'natural'], dtype=object)>, 'cf_user_maxval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'cf_user_minval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'cf_user_nvals': <tf.Tensor: shape=(1,), dtype=int64, numpy=array([1])>, 'irreg_exp': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>, 'irreg_exp_synth_maxval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'irreg_exp_synth

#### Loading tfrecords in a directory

In [6]:
# Provide a relative path to read a directory of TFrecords
tfdir = "sampleDir"
tfr.__readDirectory__(tfdir)

{'audio': <tf.Tensor: shape=(32000,), dtype=float32, numpy=array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)>, 'cf': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([317.77777], dtype=float32)>, 'cf_synth_maxval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'cf_synth_minval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'cf_synth_units': <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'natural'], dtype=object)>, 'cf_user_maxval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'cf_user_minval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'cf_user_nvals': <tf.Tensor: shape=(1,), dtype=int64, numpy=array([1])>, 'irreg_exp': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.8888889], dtype=float32)>, 'irreg_exp_synth_maxval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'irreg_exp_synth_minval': <tf.Tensor: shape=(1,), dtype=floa

{'audio': <tf.Tensor: shape=(32000,), dtype=float32, numpy=
array([0.        , 0.17135069, 0.33850297, ..., 0.        , 0.        ,
       0.        ], dtype=float32)>, 'cf': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([391.1111], dtype=float32)>, 'cf_synth_maxval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'cf_synth_minval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'cf_synth_units': <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'natural'], dtype=object)>, 'cf_user_maxval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'cf_user_minval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'cf_user_nvals': <tf.Tensor: shape=(1,), dtype=int64, numpy=array([1])>, 'irreg_exp': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>, 'irreg_exp_synth_maxval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'irreg_exp_s

{'audio': <tf.Tensor: shape=(32000,), dtype=float32, numpy=
array([0.        , 0.        , 0.        , ..., 0.67327565, 0.62235934,
       0.55452913], dtype=float32)>, 'cf': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([415.55554], dtype=float32)>, 'cf_synth_maxval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'cf_synth_minval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'cf_synth_units': <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'natural'], dtype=object)>, 'cf_user_maxval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'cf_user_minval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'cf_user_nvals': <tf.Tensor: shape=(1,), dtype=int64, numpy=array([1])>, 'irreg_exp': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.5555556], dtype=float32)>, 'irreg_exp_synth_maxval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'irr

{'audio': <tf.Tensor: shape=(32000,), dtype=float32, numpy=array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)>, 'cf': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([268.8889], dtype=float32)>, 'cf_synth_maxval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'cf_synth_minval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'cf_synth_units': <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'natural'], dtype=object)>, 'cf_user_maxval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'cf_user_minval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'cf_user_nvals': <tf.Tensor: shape=(1,), dtype=int64, numpy=array([1])>, 'irreg_exp': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.44444445], dtype=float32)>, 'irreg_exp_synth_maxval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'irreg_exp_synth_minval': <tf.Tensor: shape=(1,), dtype=floa

{'audio': <tf.Tensor: shape=(32000,), dtype=float32, numpy=
array([ 0.        ,  0.        ,  0.        , ..., -0.26675916,
       -0.10353484,  0.06268128], dtype=float32)>, 'cf': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([440.], dtype=float32)>, 'cf_synth_maxval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'cf_synth_minval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'cf_synth_units': <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'natural'], dtype=object)>, 'cf_user_maxval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'cf_user_minval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'cf_user_nvals': <tf.Tensor: shape=(1,), dtype=int64, numpy=array([1])>, 'irreg_exp': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.33333334], dtype=float32)>, 'irreg_exp_synth_maxval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'i