In [1]:
from tfrecordManager import tfrecordManager

#### Loads tfrecords for audio datasets in Patset.

In [2]:
tfr = tfrecordManager()

In [10]:
# Take a single record from a file
filename = ["sampleDir/shard0.tfrecord"]
data_record = tfr.__printRecord__(filename[0])
data_record

features {
  feature {
    key: "audio"
    value {
      float_list {
        value: 0.0
        value: 0.08108890056610107
        value: 0.16147494316101074
        value: 0.2405710071325302
        value: 0.3177880644798279
        value: 0.3925514221191406
        value: 0.46430495381355286
        value: 0.532515287399292
        value: 0.5966757535934448
        value: 0.6563102006912231
        value: 0.7109766602516174
        value: 0.7602702379226685
        value: 0.8038266897201538
        value: 0.8413247466087341
        value: 0.8724886178970337
        value: 0.8970900774002075
        value: 0.9149501323699951
        value: 0.9259403944015503
        value: 0.929983913898468
        value: 0.9270558953285217
        value: 0.9171838164329529
        value: 0.9004471898078918
        value: 0.8769769072532654
        value: 0.8469544053077698
        value: 0.8106101155281067
        value: 0.768221914768219
        value: 0.7201127409934998
        value: 0.666648447

#### Load single records

In [11]:
# Get feature list as JSON
tfr.__getFeatures__(data_record)

[['cf_synth_maxval', 'float_list'],
 ['irreg_exp', 'float_list'],
 ['irreg_exp_user_nvals', 'int64_list'],
 ['irreg_exp_synth_minval', 'float_list'],
 ['irreg_exp_user_minval', 'float_list'],
 ['cf_user_minval', 'float_list'],
 ['irreg_exp_synth_maxval', 'float_list'],
 ['segmentNum', 'int64_list'],
 ['soundDuration', 'float_list'],
 ['rate_exp_synth_units', 'bytes_list'],
 ['irreg_exp_synth_units', 'bytes_list'],
 ['pfname', 'bytes_list'],
 ['rate_exp_user_maxval', 'float_list'],
 ['rate_exp_synth_maxval', 'float_list'],
 ['rate_exp', 'float_list'],
 ['rate_exp_synth_minval', 'float_list'],
 ['cf', 'float_list'],
 ['rate_exp_user_minval', 'float_list'],
 ['irreg_exp_user_maxval', 'float_list'],
 ['cf_user_nvals', 'int64_list'],
 ['audio', 'float_list'],
 ['rate_exp_user_nvals', 'int64_list'],
 ['cf_synth_units', 'bytes_list'],
 ['cf_user_maxval', 'float_list'],
 ['cf_synth_minval', 'float_list']]

In [12]:
# Use feature list to read serialized TFrecords
tfr.__readOne__(filename)

{'audio': <tf.Tensor: shape=(32000,), dtype=float32, numpy=
array([0.        , 0.0810889 , 0.16147494, ..., 0.        , 0.        ,
       0.        ], dtype=float32)>, 'cf': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([220.], dtype=float32)>, 'cf_synth_maxval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'cf_synth_minval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'cf_synth_units': <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'natural'], dtype=object)>, 'cf_user_maxval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'cf_user_minval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'cf_user_nvals': <tf.Tensor: shape=(1,), dtype=int64, numpy=array([1])>, 'irreg_exp': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>, 'irreg_exp_synth_maxval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'irreg_exp_synth

#### Loading tfrecords in a directory

In [13]:
# Provide a relative path to read a directory of TFrecords
tfdir = "sampleDir"
tfr.__readDirectory__(tfdir)

{'audio': <tf.Tensor: shape=(32000,), dtype=float32, numpy=array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)>, 'cf': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([317.77777], dtype=float32)>, 'cf_synth_maxval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'cf_synth_minval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'cf_synth_units': <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'natural'], dtype=object)>, 'cf_user_maxval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'cf_user_minval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'cf_user_nvals': <tf.Tensor: shape=(1,), dtype=int64, numpy=array([1])>, 'irreg_exp': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.8888889], dtype=float32)>, 'irreg_exp_synth_maxval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'irreg_exp_synth_minval': <tf.Tensor: shape=(1,), dtype=floa

{'audio': <tf.Tensor: shape=(32000,), dtype=float32, numpy=array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)>, 'cf': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([220.], dtype=float32)>, 'cf_synth_maxval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'cf_synth_minval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'cf_synth_units': <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'natural'], dtype=object)>, 'cf_user_maxval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'cf_user_minval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'cf_user_nvals': <tf.Tensor: shape=(1,), dtype=int64, numpy=array([1])>, 'irreg_exp': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.8888889], dtype=float32)>, 'irreg_exp_synth_maxval': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([inf], dtype=float32)>, 'irreg_exp_synth_minval': <tf.Tensor: shape=(1,), dtype=float32, 